logging:
  config: classpath:logback.xml
server:
  port: 8081
  session: 7200
#  servlet:
#    context-path: /powerdoc
spring:
  application:
    name: powerdoc
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.95.232.65:3306/powerdoc?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
#    url: jdbc:mysql://127.0.0.1:3306/powerdoc?useSSL=false&characterEncoding=utf8
    username: root
    password: Putron2019!

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml


swagger:
  print-init: true #非必需,默认false
  enabled: true #必需
  docket:
    base-package: com.putorn.powerdoc.web   #必需